[tool.poetry]
name = "python-project-4-django"
version = "0.1.0"
description = ""
authors = ["Svetlana Kalashnikova <serebsveta@rambler.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
dotenv = "^0.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
