# Generated by Django 5.2.3 on 2025-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_is_active_alter_mailing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
