# Generated by Django 5.2.3 on 2025-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_mailing_owner_message_owner_recipient_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Время запланированной отправки', null=True),
        ),
    ]
